version: '3.8'

services:
  madness:
    build: .
    container_name: madness_challenge
    ports:
      - "9001:9001"
    restart: unless-stopped
    networks:
      - challenge_net

networks:
  challenge_net:
    driver: bridge
