version: '3.8'

services:
  scratch:
    build: .
    container_name: scratch_challenge
    ports:
      - "8002:8002"
    restart: unless-stopped
    networks:
      - challenge_net

networks:
  challenge_net:
    driver: bridge
